### ISSUE TITLE
Cannot find asset issue during cdk bootstrap

### ISSUE THREAD

**Issue by gsivamani** [aws-samples/react-ssr-lambda#62]
Hello team!

Encountering the below error during the cdk bootstrap step. Not sure if this is a new issue. Help appreciated. Thanks

cd react-ssr-lambda
cd ./cdk
npm install
npm run build
cdk bootstrap - failed here

Error: Cannot find asset at /home/gss/myprojects/react-ssr-lambda/simple-ssr/build
    at new AssetStaging (/home/gss/myprojects/react-ssr-lambda/cdk/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:1402)
    at new Asset (/home/gss/myprojects/react-ssr-lambda/cdk/node_modules/aws-cdk-lib/aws-s3-assets/lib/asset.js:1:736)
    at Object.bind (/home/gss/myprojects/react-ssr-lambda/cdk/node_modules/aws-cdk-lib/aws-s3-deployment/lib/source.js:1:1185)
    at /home/gss/myprojects/react-ssr-lambda/cdk/node_modules/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.js:1:3013
    at Array.map (<anonymous>)
    at new BucketDeployment (/home/gss/myprojects/react-ssr-lambda/cdk/node_modules/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.js:1:2994)
    at new SsrStack (/home/gss/myprojects/react-ssr-lambda/cdk/lib/srr-stack.ts:44:5)
    at Object.<anonymous> (/home/gss/myprojects/react-ssr-lambda/cdk/bin/cdk.ts:13:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module.m._compile (/home/gss/myprojects/react-ssr-lambda/cdk/node_modules/ts-node/src/index.ts:1618:23)

**Comment by glinisdev** [comment]
Same issue. There are no proper npm commands to build react app

**Comment by mitch-c-miller** [comment]
Also ran into this issue. You can get around it by manually adding the different services yourself, but it's definitely not the intended experience for a demo

**Comment by breskeby** [comment]
Hitting the same problem. @mitch-c-miller no idea how to do that though (creating different services myself. not even sure what's required)

**Comment by mitch-c-miller** [comment]
@breskeby the different TS files in `cdk/lib` are the blueprints to create the necessary resources. For example, [this snippet](https://github.com/aws-samples/react-ssr-lambda/blob/fd61dd1d373b1cdc0b2a0126c975abad508fbee2/cdk/lib/srr-stack.ts#L44)

`BucketDeployment` creates a new S3 Bucket, with the ID `"Client-side React app"`. It uploads build artifacts from `../simple-ssr/build/` in local storage to `mySiteBucket`, which is defined [here](https://github.com/aws-samples/react-ssr-lambda/blob/fd61dd1d373b1cdc0b2a0126c975abad508fbee2/cdk/lib/srr-stack.ts#L23).

If you're unfamiliar with AWS terminology, I strongly recommend checking out some tutorials on Youtube to get a rundown on the basics. AWS has a bunch of longstanding product names that are clever and cute when you know what they mean, but they're not useful otherwise (e.g. Route 53 is DNS since DNS uses port 53). AWS is _dense_ and complicated, but the core concepts will get you very far!

**Comment by mitch-c-miller** [comment]
[This should also be a more useful guide.](https://aws.amazon.com/getting-started/hands-on/build-serverless-web-app-lambda-apigateway-s3-dynamodb-cognito/) It's actively maintained by AWS and includes more useful features like Cognito.

**Comment by LandonS777** [comment]
I resolved this issue by doing a few additional steps outside of the readme provided. I would suggest followings these steps before any of the steps given in the readme:

- cd react-ssr-lambda
- cd simple-ssr/
- npm install
- npm run build (build might fail if no config.json is found in the src dir, just create one)
- cd ..
- cd ./cdk/

From this point follow the directions in the readme. Doing this resolved the issue for me. The steps above are ensuring that the simple-ssr/build directory exists and is created.

**Comment by 4leafproductions** [comment]
> I resolved this issue by doing a few additional steps outside of the readme provided. I would suggest followings these steps before any of the steps given in the readme:
> 
>     * cd react-ssr-lambda
> 
>     * cd simple-ssr/
> 
>     * npm install
> 
>     * npm run build (build might fail if no config.json is found in the src dir, just create one)
> 
>     * cd ..
> 
>     * cd ./cdk/
> 
> 
> From this point follow the directions in the readme. Doing this resolved the issue for me. The steps above are ensuring that the simple-ssr/build directory exists and is created.

Hey, I had the thought to do this but I doubted myself... you gave me the confidence to proceed and it worked, so THANK YOU.
